# Efficient Computing with NumPy - Jake Vanderplas

In [2]:
def func(N):
    d = 0.
    for i in range(N):
        d += (i%3 - 1) *i
    return d

%timeit func(10000)

1000 loops, best of 3: 1.6 ms per loop


17,9 micro.s for fortran

- each operations comes with small type-checking overheadd
- reference operation

numpy is desidned for :

- fast developement time of python
- fast execution time of C/fortran
by pushing repeated operations into a statically-type

4 strategies:

- use ufunc
- use aggregating
- use broadcasting
- use slicing, masking and fancy indexing

Overall goal: 
Push repeated operations into compiled code and * **get rid of slow loops** *

## Ufunc

element-wise operations

In [4]:
import numpy as np

a = list(range(100000))
%timeit [val+5 for val in a]

a = np.array(a)
%timeit a+5

100 loops, best of 3: 5.36 ms per loop
10000 loops, best of 3: 117 µs per loop


- arithmetic : + - * / // % **
- bitwise : & | ~ ^ >> <<
- Comparison : > < >= <= == !=
- trig
- exp
- special

## Aggregations

functions which summarize the values in an array :
min, max, sum, mean...

In [6]:
from random import random
c = [random() for i in range(100000)]

%timeit min(c)

c = np.array(c)
%timeit c.min()

100 loops, best of 3: 2.71 ms per loop
The slowest run took 37.50 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 104 µs per loop


In [9]:
M = np.random.randint(1,10,(3,5))
print M
print ' '
print M.sum()
print ' '
print M.sum(axis=0)
print M.sum(axis=1)

[[2 4 4 6 1]
 [1 3 5 8 6]
 [8 4 2 7 9]]
 
70
 
[11 11 11 21 16]
[17 23 30]


## Broadcasting

set of rules by whitch ufunc operate on arrays of sizes and/or dimensions

In [13]:
a = np.arange(3) + 1
b = np.ones((3,3)) + np.arange(3)
c = np.arange(3)
c = c.reshape((3,1)) + c

print a
print ' '
print b
print ' '
print c

[1 2 3]
 
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
 
[[0 1 2]
 [1 2 3]
 [2 3 4]]


Rule of broadcasting :

- 1: if array shapes differ, lef-pad the smaller shape with 1s
- 2: if any dimension does not match, broadcast the dimension with size 1
- 3: if neither non-matching dimension is 1, raise error

## Slicing, masking, fancy index

In [17]:
L = [1,2,3,4,5]
print L[0], L[1:-2]

1 [2, 3]


In [1]:
l = np.arange(12)
mask = (l < 4) | (l > 8)
l[mask]

NameError: name 'np' is not defined

In [73]:
l[[0,2,4,6,8]]

array([0, 2, 4, 6, 8])

In [83]:
l = np.arange(6).reshape(2,3)
l[l.sum(axis=1) > 4, 1:]

array([[4, 5]])